const sceneFewShotExamples = [
  {
    user: '画一间房子，旁边有一棵树，右上角有太阳',
    output: {
      action: 'scene',
      title: '房子、树和太阳',
      sourceText: '画一间房子，旁边有一棵树，右上角有太阳',
      elements: [
        {
          id: 'ground-line',
          groupId: 'ground-1',
          groupLabel: '地面',
          partLabel: '地平线',
          shape: 'line',
          color: 'green',
          bbox: { x: 90, y: 500, width: 820, height: 0 },
          zIndex: 1,
        },
        {
          id: 'house-wall',
          groupId: 'house-1',
          groupLabel: '房子',
          partLabel: '墙体',
          shape: 'rect',
          color: 'orange',
          bbox: { x: 420, y: 330, width: 240, height: 170 },
          zIndex: 10,
        },
        {
          id: 'house-roof',
          groupId: 'house-1',
          groupLabel: '房子',
          partLabel: '屋顶',
          shape: 'triangle',
          color: 'red',
          bbox: { x: 380, y: 235, width: 320, height: 130 },
          zIndex: 12,
        },
        {
          id: 'house-door',
          groupId: 'house-1',
          groupLabel: '房子',
          partLabel: '门',
          shape: 'rect',
          color: 'black',
          bbox: { x: 520, y: 410, width: 54, height: 90 },
          zIndex: 14,
        },
        {
          id: 'house-window-left',
          groupId: 'house-1',
          groupLabel: '房子',
          partLabel: '窗户',
          shape: 'rect',
          color: 'blue',
          bbox: { x: 450, y: 365, width: 46, height: 42 },
          zIndex: 14,
        },
        {
          id: 'tree-trunk',
          groupId: 'tree-1',
          groupLabel: '树',
          partLabel: '树干',
          shape: 'rect',
          color: 'orange',
          bbox: { x: 260, y: 395, width: 48, height: 105 },
          zIndex: 8,
        },
        {
          id: 'tree-crown',
          groupId: 'tree-1',
          groupLabel: '树',
          partLabel: '树冠',
          shape: 'circle',
          color: 'green',
          bbox: { x: 215, y: 285, width: 140, height: 140 },
          zIndex: 11,
        },
        {
          id: 'sun-core',
          groupId: 'sun-1',
          groupLabel: '太阳',
          partLabel: '主体',
          shape: 'circle',
          color: 'yellow',
          bbox: { x: 790, y: 70, width: 100, height: 100 },
          zIndex: 20,
        },
      ],
    },
  },
  {
    user: '画一个生日派对，有蛋糕、气球和桌子',
    output: {
      action: 'scene',
      title: '生日派对',
      sourceText: '画一个生日派对，有蛋糕、气球和桌子',
      elements: [
        {
          id: 'table-top',
          groupId: 'table-1',
          groupLabel: '桌子',
          partLabel: '桌面',
          shape: 'rect',
          color: 'orange',
          bbox: { x: 250, y: 405, width: 500, height: 55 },
          zIndex: 6,
        },
        {
          id: 'table-left-leg',
          groupId: 'table-1',
          groupLabel: '桌子',
          partLabel: '桌腿',
          shape: 'rect',
          color: 'black',
          bbox: { x: 305, y: 455, width: 35, height: 95 },
          zIndex: 5,
        },
        {
          id: 'table-right-leg',
          groupId: 'table-1',
          groupLabel: '桌子',
          partLabel: '桌腿',
          shape: 'rect',
          color: 'black',
          bbox: { x: 660, y: 455, width: 35, height: 95 },
          zIndex: 5,
        },
        {
          id: 'cake-bottom',
          groupId: 'cake-1',
          groupLabel: '蛋糕',
          partLabel: '底层',
          shape: 'rect',
          color: 'purple',
          bbox: { x: 405, y: 330, width: 190, height: 75 },
          zIndex: 12,
        },
        {
          id: 'cake-top',
          groupId: 'cake-1',
          groupLabel: '蛋糕',
          partLabel: '上层',
          shape: 'rect',
          color: 'white',
          bbox: { x: 440, y: 285, width: 120, height: 55 },
          zIndex: 13,
        },
        {
          id: 'candle-one',
          groupId: 'cake-1',
          groupLabel: '蛋糕',
          partLabel: '蜡烛',
          shape: 'rect',
          color: 'yellow',
          bbox: { x: 475, y: 245, width: 16, height: 42 },
          zIndex: 15,
        },
        {
          id: 'candle-two',
          groupId: 'cake-1',
          groupLabel: '蛋糕',
          partLabel: '蜡烛',
          shape: 'rect',
          color: 'yellow',
          bbox: { x: 515, y: 245, width: 16, height: 42 },
          zIndex: 15,
        },
        {
          id: 'balloon-left',
          groupId: 'balloon-1',
          groupLabel: '气球',
          partLabel: '左气球',
          shape: 'circle',
          color: 'red',
          bbox: { x: 180, y: 120, width: 90, height: 120 },
          zIndex: 18,
        },
        {
          id: 'balloon-left-string',
          groupId: 'balloon-1',
          groupLabel: '气球',
          partLabel: '绳子',
          shape: 'line',
          color: 'gray',
          bbox: { x: 225, y: 235, width: 20, height: 145 },
          zIndex: 17,
        },
        {
          id: 'balloon-right',
          groupId: 'balloon-2',
          groupLabel: '气球',
          partLabel: '右气球',
          shape: 'circle',
          color: 'blue',
          bbox: { x: 740, y: 115, width: 90, height: 120 },
          zIndex: 18,
        },
        {
          id: 'balloon-right-string',
          groupId: 'balloon-2',
          groupLabel: '气球',
          partLabel: '绳子',
          shape: 'line',
          color: 'gray',
          bbox: { x: 770, y: 230, width: 20, height: 145 },
          zIndex: 17,
        },
      ],
    },
  },
  {
    user: '画一座桥，下面有河，天上有云',
    output: {
      action: 'scene',
      title: '桥、河和云',
      sourceText: '画一座桥，下面有河，天上有云',
      elements: [
        {
          id: 'river-main',
          groupId: 'river-1',
          groupLabel: '河',
          partLabel: '河面',
          shape: 'rect',
          color: 'blue',
          bbox: { x: 70, y: 420, width: 860, height: 105 },
          zIndex: 2,
        },
        {
          id: 'bridge-deck',
          groupId: 'bridge-1',
          groupLabel: '桥',
          partLabel: '桥面',
          shape: 'rect',
          color: 'orange',
          bbox: { x: 210, y: 345, width: 580, height: 45 },
          zIndex: 10,
        },
        {
          id: 'bridge-left-pillar',
          groupId: 'bridge-1',
          groupLabel: '桥',
          partLabel: '桥墩',
          shape: 'rect',
          color: 'gray',
          bbox: { x: 285, y: 385, width: 55, height: 105 },
          zIndex: 9,
        },
        {
          id: 'bridge-right-pillar',
          groupId: 'bridge-1',
          groupLabel: '桥',
          partLabel: '桥墩',
          shape: 'rect',
          color: 'gray',
          bbox: { x: 660, y: 385, width: 55, height: 105 },
          zIndex: 9,
        },
        {
          id: 'bridge-arch',
          groupId: 'bridge-1',
          groupLabel: '桥',
          partLabel: '拱形',
          shape: 'triangle',
          color: 'white',
          bbox: { x: 390, y: 390, width: 220, height: 90 },
          zIndex: 11,
        },
        {
          id: 'cloud-left-a',
          groupId: 'cloud-1',
          groupLabel: '云',
          partLabel: '云朵',
          shape: 'circle',
          color: 'white',
          bbox: { x: 165, y: 95, width: 95, height: 65 },
          zIndex: 20,
        },
        {
          id: 'cloud-left-b',
          groupId: 'cloud-1',
          groupLabel: '云',
          partLabel: '云朵',
          shape: 'circle',
          color: 'white',
          bbox: { x: 225, y: 80, width: 115, height: 80 },
          zIndex: 20,
        },
        {
          id: 'cloud-left-c',
          groupId: 'cloud-1',
          groupLabel: '云',
          partLabel: '云朵',
          shape: 'circle',
          color: 'white',
          bbox: { x: 310, y: 105, width: 90, height: 60 },
          zIndex: 20,
        },
      ],
    },
  },
]

export function buildSceneFewShotPrompt() {
  return sceneFewShotExamples
    .map((example, index) =>
      [
        `Scene example ${index + 1} user command: ${example.user}`,
        `Scene example ${index + 1} JSON: ${JSON.stringify(example.output)}`,
      ].join('\n'),
    )
    .join('\n')
}
