import type { CanvasState } from './types'

export const sampleCanvas: CanvasState = {
  width: 960,
  height: 560,
  selectedId: 'sun',
  history: [],
  future: [],
  shapes: [
    {
      id: 'sky-label',
      type: 'text',
      x: 56,
      y: 58,
      width: 220,
      height: 40,
      fill: '#1f2937',
      stroke: 'transparent',
      text: 'Voice-built scene draft',
    },
    {
      id: 'house-body',
      type: 'rect',
      x: 356,
      y: 278,
      width: 220,
      height: 160,
      fill: '#f4a261',
      stroke: '#7c2d12',
      strokeWidth: 3,
    },
    {
      id: 'house-roof',
      type: 'triangle',
      x: 326,
      y: 178,
      width: 280,
      height: 130,
      fill: '#b91c1c',
      stroke: '#7f1d1d',
      strokeWidth: 3,
    },
    {
      id: 'door',
      type: 'rect',
      x: 438,
      y: 348,
      width: 56,
      height: 90,
      fill: '#7c3f16',
      stroke: '#3f1d0b',
      strokeWidth: 2,
    },
    {
      id: 'tree-trunk',
      type: 'rect',
      x: 200,
      y: 332,
      width: 42,
      height: 108,
      fill: '#8b5a2b',
      stroke: '#4b2e15',
      strokeWidth: 2,
    },
    {
      id: 'tree-crown',
      type: 'circle',
      x: 164,
      y: 228,
      width: 112,
      height: 112,
      fill: '#2f855a',
      stroke: '#14532d',
      strokeWidth: 3,
    },
    {
      id: 'sun',
      type: 'circle',
      x: 748,
      y: 82,
      width: 96,
      height: 96,
      fill: '#facc15',
      stroke: '#ca8a04',
      strokeWidth: 3,
    },
    {
      id: 'ground',
      type: 'line',
      x: 84,
      y: 440,
      width: 792,
      height: 0,
      fill: 'transparent',
      stroke: '#3f6212',
      strokeWidth: 6,
    },
  ],
}
